# Generated by Django 4.1 on 2022-11-17 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Descriptions')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Added on Date')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('date_completed', models.DateTimeField(auto_now=True, verbose_name='Completed at')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': "Task's",
                'ordering': ['-date_created', 'completed'],
            },
        ),
    ]
